Arm timer fix
au-ts/sddf pull request #208
Opened 2024-08-15 05:36 UTC by Kswin01

Fix for https://github.com/au-ts/sddf/issues/178. Adding in support for 128 bit integer division, as we do not have this as part of clang with no std lib. It does however exist in libgcc, but as we are moving away from gcc, this is a temporary fix before writing our own libc.

The multiplication should not overflow for approx ~10 trillion years instead of 5-10 minutes.

2024-08-15 06:27 UTC, abrandnewusername submitted a review, later dismissed

2024-08-28 01:39 UTC, wom-bat requested changes
Very minor changes needed (mostly cosmetic)

2024-08-28 01:39 UTC, wom-bat commented on drivers/clock/arm/timer.c
> +    uint64_t res = udiv128by64to64(ncycles_in_s >> 64, ncycles_in_s & 0xffffffffffffffff, NS_IN_S, &rem);
Make that 0xffffffffffffffffULL, or just cast to a 64-bit number.
`udiv128by64to64(ncycles_in_s >> 64, (uint64_t)ncycyles_in_s, NS_IN_S, &rem)`
or create some helper macros to extract high/low 64-bit words from a 128bit value

2024-08-28 01:39 UTC, wom-bat commented on drivers/clock/arm/timer.c
> +    uint64_t res = udiv128by64to64(calc >> 64, calc & 0xffffffffffffffff, NS_IN_S, &rem);
Again.  Looks like a pair of `low_word() high_word()` macros might be useful

2024-09-06 02:28 UTC, Ivan-Velickovic commented on util/udivmodti4.c
Is this getting compiled anywhere? Do we only use `udivmodti4.h`?

2024-09-06 02:28 UTC, Ivan-Velickovic commented on drivers/clock/arm/timer.c
> +    sddf_dprintf("This is timer freq: %lu\n", timer_freq);
Is this a leftover debug print?

2024-09-17 02:32 UTC, Ivan-Velickovic approved these changes

2024-09-17 02:32 UTC, merged