ci: add echo_server for imx8mp_evk
au-ts/sddf pull request #233
Opened 2024-09-04 06:02 UTC by Ivan-Velickovic

2024-09-04 06:03 UTC, wom-bat submitted a review, later dismissed
Looks good.

2024-09-04 06:03 UTC, Kswin01 commented on ci/examples.sh
> +    BOARDS=("odroidc4" "imx8mm_evk" "imx8mp_evk "maaxboard" "qemu_virt_aarch64")
missing "?

2024-09-04 06:06 UTC, Kswin01 approved these changes

2024-09-04 09:39 UTC, wom-bat requested changes
Suggest splitting off the microkit obtaining patches from this PR.  Make this one _just_ add the imxp8mp_evk

2024-09-04 09:39 UTC, wom-bat commented on .github/workflows/examples.yaml
> +          mv microkit-sdk-*/ microkit-sdk
These look like unrelated changes.

2024-09-04 09:39 UTC, wom-bat commented on .github/workflows/examples.yaml
> +          mv microkit-sdk-*/ microkit-sdk
As do these

2024-09-04 10:01 UTC, Ivan-Velickovic commented
The support for `imx8mp_evk` doesn't exist in a released version of Microkit so the patch needs to also acquire the latest commit of the SDK.

2025-01-14 02:48 UTC, Ivan-Velickovic commented
Closing since this will be done in https://github.com/au-ts/sddf/pull/298.

2025-01-14 02:48 UTC, closed without merging