net: adhere to new naming
au-ts/sDDF pull request #58
Opened 2024-03-15 00:37 UTC by Ivan-Velickovic

2024-03-19 01:46 UTC, wom-bat requested changes

2024-03-19 01:46 UTC, wom-bat commented on network/queue/queue.c
Get rid of this file; include `net_queue_init` as a static inline in queue.h

2024-03-19 02:05 UTC, Ivan-Velickovic commented on network/queue/queue.c
done

2024-03-19 04:01 UTC, wom-bat requested changes
Found some more ring->queue changes needed

2024-03-19 04:01 UTC, wom-bat commented on network/components/virt_tx.c
> +    net_queue_handle_t tx_ring_drv;
`tx_queue_drv` and `tx_quque_clients`

2024-03-20 05:11 UTC, Ivan-Velickovic commented
Okay, I think I've got all of them, now...

2024-03-21 21:02 UTC, wom-bat requested changes

2024-03-21 21:02 UTC, wom-bat commented on include/sddf/network/queue.h
> +    uintptr_t phys_or_offset;
In fact the way these are used assumes a single mapping --- the virtualisers will not work if the region is not contiguous.

2024-03-21 21:53 UTC, wom-bat approved these changes
Looks good now.

2024-03-22 00:06 UTC, Ivan-Velickovic commented on drivers/network/meson/ethernet.c
>  volatile struct eth_mac_regs *eth_mac = (void *)(uintptr_t)0x2000000;
It's a virtual address, I don't know why the code is like this is can just use `setvar_vaddr` like everything else I think.

2024-03-23 12:37 UTC, Courtney3141 commented on drivers/network/meson/ethernet.c
>  volatile struct eth_mac_regs *eth_mac = (void *)(uintptr_t)0x2000000;
I noticed this recently and was planning on updating it.

2024-03-23 12:56 UTC, Courtney3141 commented
I have just checked the memory barriers in queue.h, everything looks good to me. I built for both the odroidc4 and the imx8mm and ran some benchmarks - everything performed as per usual. I am happy to merge this pull request.

2024-03-23 12:57 UTC, merged